[package]
name = "crate-test-2"
version = "0.1.0"
authors = ["booink <booink.work@gmail.com>"]
readme = "../README.md"
repository = "https://github.com/booink/public-crate"
description = """
Crate test 2
"""
edition = "2018"
